const nutritionPlants = [
["Tomato","Vitamin C","Immunity","18 kcal","Raw"],
["Spinach","Iron","Blood","23 kcal","Cooked"],
["Carrot","Vitamin A","Eyes","41 kcal","Raw"],
["Banana","Potassium","Energy","89 kcal","Raw"],
["Apple","Fiber","Digestion","52 kcal","Raw"],
["Orange","Vitamin C","Skin","47 kcal","Juice"],
["Papaya","Enzymes","Digestion","43 kcal","Raw"],
["Mango","Vitamin A","Growth","60 kcal","Raw"],
["Guava","Vitamin C","Immunity","68 kcal","Raw"],
["Potato","Carbs","Energy","77 kcal","Boiled"],
["Cucumber","Water","Hydration","16 kcal","Raw"],
["Pomegranate","Antioxidants","Heart","83 kcal","Raw"],
["Broccoli","Fiber","Cancer prevention","34 kcal","Cooked"],
["Cauliflower","Vitamin K","Bones","25 kcal","Cooked"],
["Peas","Protein","Muscle","81 kcal","Cooked"],
["Sweet Potato","Vitamin A","Eyes","86 kcal","Boiled"],
["Beetroot","Iron","Blood","43 kcal","Raw"],
["Cabbage","Vitamin C","Immunity","25 kcal","Cooked"],
["Onion","Antioxidants","Heart","40 kcal","Raw"],
["Garlic","Sulfur","Immunity","149 kcal","Raw"],
["Avocado","Healthy fats","Heart","160 kcal","Raw"],
["Pumpkin","Vitamin A","Skin","26 kcal","Cooked"],
["Lettuce","Fiber","Digestion","15 kcal","Raw"],
["Okra","Fiber","Diabetes","33 kcal","Cooked"],
["Radish","Vitamin C","Detox","16 kcal","Raw"],
["Corn","Carbs","Energy","86 kcal","Boiled"],
["Chickpeas","Protein","Muscle","164 kcal","Boiled"],
["Lentils","Protein","Blood","116 kcal","Cooked"],
["Soybean","Protein","Bones","446 kcal","Cooked"],
["Almond","Vitamin E","Brain","579 kcal","Raw"],
["Walnut","Omega-3","Heart","654 kcal","Raw"],
["Cashew","Minerals","Energy","553 kcal","Raw"],
["Dates","Iron","Energy","282 kcal","Raw"],
["Raisins","Iron","Blood","299 kcal","Raw"],
["Strawberry","Vitamin C","Skin","32 kcal","Raw"],
["Blueberry","Antioxidants","Brain","57 kcal","Raw"],
["Kiwi","Vitamin C","Immunity","61 kcal","Raw"],
["Pineapple","Enzymes","Digestion","50 kcal","Raw"],
["Watermelon","Hydration","Cooling","30 kcal","Raw"],
["Chia Seeds","Omega-3","Heart","486 kcal","Soaked"],
["Flax Seeds","Fiber","Digestion","534 kcal","Ground"],
["Oats","Fiber","Heart","389 kcal","Cooked"],
["Brown Rice","Carbs","Energy","123 kcal","Cooked"],
["Quinoa","Protein","Muscle","120 kcal","Cooked"],
["Barley","Fiber","Cholesterol","354 kcal","Cooked"],
["Millets","Minerals","Energy","378 kcal","Cooked"]
];
